In [1]:
# Input bags
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [18]:
# Input data
path='C:\\Users\\YWANG418\\Documents\\Job\\Machine Learning\\Regression\\longley.csv'
data=pd.read_csv(path,header=None)
x=data.iloc[1:,2:]
y=data.iloc[1:,1]

          2      3      4        5     6       7
1   234.289  235.6    159  107.608  1947  60.323
2   259.426  232.5  145.6  108.632  1948  61.122
3   258.054  368.2  161.6  109.773  1949  60.171
4   284.599  335.1    165  110.929  1950  61.187
5   328.975  209.9  309.9  112.075  1951  63.221
6   346.999  193.2  359.4   113.27  1952  63.639
7   365.385    187  354.7  115.094  1953  64.989
8   363.112  357.8    335  116.219  1954  63.761
9   397.469  290.4  304.8  117.388  1955  66.019
10   419.18  282.2  285.7  118.734  1956  67.857
11  442.769  293.6  279.8  120.445  1957  68.169
12  444.546  468.1  263.7   121.95  1958  66.513
13  482.704  381.3  255.2  123.366  1959  68.655
14  502.601  393.1  251.4  125.368  1960  69.564
15  518.173  480.6  257.2  127.852  1961  69.331
16  554.894  400.7  282.7  130.081  1962  70.551

In [19]:
#Build Model
model=linear_model.LassoCV()
model.fit(x,y)

#Lasso lam
print(model.alpha_)
#Coef
print(model.coef_)

20.03464209711722
[0.10206856 0.00409161 0.00354815 0.         0.         0.        ]

In [24]:
#predict
x_test=x.iloc[-2,:]
model.predict(x_test[np.newaxis,:])

array([115.6461414])